/**
 * Catalogo de procedimientos odontologicos - Anexo 2 del Manual del Formulario 033 (MSP Ecuador).
 * Nomenclatura CDT (D0100-D0999), segun el documento oficial de referencia.
 */
export interface ProcedimientoOdontologico {
  codigo: string;
  descripcion: string;
}

export const PROCEDIMIENTOS_ODONTOLOGICOS: ProcedimientoOdontologico[] = [
  { codigo: "D0120", descripcion: "peri\u00f3dica evaluaci\u00f3n oral \u2013 paciente subsecuente" },
  { codigo: "D0140", descripcion: "limitada evaluaci\u00f3n oral - problema centrado" },
  { codigo: "D0145", descripcion: "Evaluaci\u00f3n oral a un paciente menor de tres a\u00f1os de edad y asesoramiento, con primaria o cuidador" },
  { codigo: "D0150", descripcion: "completa evaluaci\u00f3n oral - o establecidos nuevo paciente" },
  { codigo: "D0160", descripcion: "extensa evaluaci\u00f3n detallada y oral - problema se centr\u00f3, en el informe" },
  { codigo: "D0170", descripcion: "re-evaluaci\u00f3n - limitada, el problema se centr\u00f3 (paciente establecido, no-operatorio visita post)" },
  { codigo: "D0180", descripcion: "evaluaci\u00f3n periodontal completa - o establecidos nuevo paciente" },
  { codigo: "D0210", descripcion: "Serie completa (incluyendo proyecciones de mordida)" },
  { codigo: "D0220", descripcion: "intraoral - primera pel\u00edcula periapical intraoral" },
  { codigo: "D0230", descripcion: "cada radiograf\u00eda periapical adicional intraoral" },
  { codigo: "D0240", descripcion: "oclusal pel\u00edcula extraoral" },
  { codigo: "D0250", descripcion: "primera pel\u00edcula" },
  { codigo: "D0260", descripcion: "extraoral - cada pel\u00edcula adicional mordida" },
  { codigo: "D0270", descripcion: "sola pel\u00edcula mordida" },
  { codigo: "D0272", descripcion: "dos pel\u00edculas mordida" },
  { codigo: "D0273", descripcion: "tres pel\u00edculas" },
  { codigo: "D0274", descripcion: "mordida - cuatro pel\u00edculas" },
  { codigo: "D0277", descripcion: "mordida vertical - 7 a 8 pel\u00edculas" },
  { codigo: "D0290", descripcion: "postero-anterior o lateral del cr\u00e1neo y los huesos faciales encuesta pel\u00edcula" },
  { codigo: "D0310", descripcion: "sialograf\u00eda" },
  { codigo: "D0320", descripcion: "-temporomandibular artrograma conjunta, incluyendo la inyecci\u00f3n" },
  { codigo: "D0321", descripcion: "otra articulaci\u00f3n temporomandibular pel\u00edculas, por el informe encuesta tomogr\u00e1fica" },
  { codigo: "D0330", descripcion: "panor\u00e1micas de cine" },
  { codigo: "D0340", descripcion: "cefalom\u00e9trico pel\u00edcula" },
  { codigo: "D0350", descripcion: "oral / facial im\u00e1genes fotogr\u00e1ficas TC de haz c\u00f3nico" },
  { codigo: "D0360", descripcion: "TC de haz c\u00f3nico- los datos de captura craneofacial haz de cono" },
  { codigo: "D0362", descripcion: "- reconstrucci\u00f3n de la imagen tridimensional y dos a partir de datos existentes, incluye m\u00faltiples im\u00e1genes haz de cono" },
  { codigo: "D0363", descripcion: "- reconstrucci\u00f3n de la imagen tridimensional y tres a partir de datos existentes, incluye m\u00faltiples im\u00e1genes." },
  { codigo: "D0415", descripcion: "colecci\u00f3n de microorganismos para la cultura y la sensibilidad" },
  { codigo: "D0416", descripcion: "cultivo viral" },
  { codigo: "D0417", descripcion: "recogida y preparaci\u00f3n de muestra de saliva para ensayos de laboratorio de diagn\u00f3stico" },
  { codigo: "D0418", descripcion: "an\u00e1lisis de muestras de saliva" },
  { codigo: "D0421", descripcion: "prueba gen\u00e9tica para la susceptibilidad a las enfermedades bucodentales" },
  { codigo: "D0425", descripcion: "pruebas de susceptibilidad a la caries" },
  { codigo: "D0431", descripcion: "pre-prueba de diagn\u00f3stico complementario que ayuda en la detecci\u00f3n de anomal\u00edas de la mucosa como y malignas las lesiones premalignas, que no incluyen la citolog\u00eda o biopsia procedimientos" },
  { codigo: "D0460", descripcion: "Pruebas de vitalidad pulpar" },
  { codigo: "D0470", descripcion: "modelos de diagn\u00f3stico" },
  { codigo: "D0472", descripcion: "adhesi\u00f3n del tejido, el examen macrosc\u00f3pico, la preparaci\u00f3n y la transmisi\u00f3n del informe escrito" },
  { codigo: "D0473", descripcion: "adhesi\u00f3n del tejido, y el examen microsc\u00f3pico bruto, la preparaci\u00f3n y transmisi\u00f3n de informe escrito" },
  { codigo: "D0474", descripcion: "adhesi\u00f3n del tejido, y el examen microsc\u00f3pico bruto, incluida la evaluaci\u00f3n de cirug\u00eda m\u00e1rgenes para la presencia de la enfermedad, la preparaci\u00f3n y la transmisi\u00f3n del informe escrito" },
  { codigo: "D0475", descripcion: "procedimiento de descalcificaci\u00f3n" },
  { codigo: "D0476", descripcion: "tinciones especiales para microorganismos" },
  { codigo: "D0477", descripcion: "tinciones especiales, no para los microorganismos" },
  { codigo: "D0478", descripcion: "inmunohistoqu\u00edmica manchas" },
  { codigo: "D0479", descripcion: "tejido situ hibridaci\u00f3n in, incluida la interpretaci\u00f3n" },
  { codigo: "D0480", descripcion: "adhesi\u00f3n de frotis citol\u00f3gico exfoliativa, el examen microsc\u00f3pico, preparaci\u00f3n y la transmisi\u00f3n del informe escrito" },
  { codigo: "D0481", descripcion: "microscop\u00eda electr\u00f3nica - de diagn\u00f3stico" },
  { codigo: "D0482", descripcion: "inmunofluorescencia directa" },
  { codigo: "D0483", descripcion: "inmunofluorescencia indirecta" },
  { codigo: "D0484", descripcion: "consulta en l\u00e1minas en otros lugares" },
  { codigo: "D0485", descripcion: "consulta, incluida la preparaci\u00f3n de los portaobjetos de material de biopsia facilitada por referencia fuente" },
  { codigo: "D0486", descripcion: "laboratorio de la adhesi\u00f3n de la biopsia Muestra de cepillado, el examen microsc\u00f3pico, preparaci\u00f3n y la transmisi\u00f3n del informe escrito" },
  { codigo: "D0502", descripcion: "procedimientos orales otra patolog\u00eda, por el informe" },
  { codigo: "D0999", descripcion: "sin especificar procedimiento de diagn\u00f3stico, el informe" },
  { codigo: "D1110", descripcion: "\u2013 profilaxis adultos" },
  { codigo: "D1120", descripcion: "\u2013 profilaxis infantil" },
  { codigo: "D1203", descripcion: "La aplicaci\u00f3n t\u00f3pica de fluoruro-infantil" },
  { codigo: "D1204", descripcion: "aplicaci\u00f3n t\u00f3pica de fluoruro - adultos" },
  { codigo: "D1206", descripcion: "topicaci\u00f3n de fluoruro barniz, la aplicaci\u00f3n terap\u00e9utica de moderado a la caries pacientes de alto riesgo" },
  { codigo: "D1310", descripcion: "diet\u00e9ticas espec\u00edficas para el control de la enfermedad dental" },
  { codigo: "D1320", descripcion: "asesoramiento del tabaco para el control y la prevenci\u00f3n de las enfermedades bucodentales" },
  { codigo: "D1330", descripcion: "instrucciones de higiene oral" },
  { codigo: "D1351", descripcion: "Sellador - por diente" },
  { codigo: "D1510", descripcion: "mantenedor de espacio - fijo - unilaterales" },
  { codigo: "D1515", descripcion: "mantenedor de espacio - fijo - bilaterales" },
  { codigo: "D1520", descripcion: "mantenedor de espacio - extra\u00edble - unilaterales" },
  { codigo: "D1525", descripcion: "mantenedor de espacio - extra\u00edble - bilaterales" },
  { codigo: "D1550", descripcion: "volver a la cementaci\u00f3n del espacio mantenedor" },
  { codigo: "D1555", descripcion: "eliminaci\u00f3n de mantenedor de espacio fijo" },
  { codigo: "D2140", descripcion: "\u2013 amalgama superficie una, primaria o permanente" },
  { codigo: "D2150", descripcion: "amalgama- dos superficies, primaria o permanente" },
  { codigo: "D2160", descripcion: "amalgama- tres superficies, primaria o permanente" },
  { codigo: "D2161", descripcion: "Amalgama - cuatro o m\u00e1s superficies, primarios o permanentes" },
  { codigo: "D2330", descripcion: "a base de resina compuesta - una superficie, anterior" },
  { codigo: "D2331", descripcion: "-a base de resinas compuestas - dos superficies, anterior" },
  { codigo: "D2332", descripcion: "-a base de resinas compuestas - tres superficies, anterior" },
  { codigo: "D2335", descripcion: "-a base de resinas compuestas - cuatro o m\u00e1s superficies o en relaci\u00f3n con el \u00e1ngulo incisal (anterior)" },
  { codigo: "D2390", descripcion: "base compuesta corona con resina, anterior" },
  { codigo: "D2391", descripcion: "a base de resina compuesta - una superficie, posterior" },
  { codigo: "D2392", descripcion: "-a base de resinas compuestas - dos superficies, posterior" },
  { codigo: "D2393", descripcion: "-a base de resinas compuestas - tres superficies, posterior" },
  { codigo: "D2394", descripcion: "-compuesto base - cuatro o m\u00e1s superficies de resina, posterior" },
  { codigo: "D2410", descripcion: "l\u00e1mina de oro - una superficie" },
  { codigo: "D2420", descripcion: "l\u00e1mina de oro - dos superficies" },
  { codigo: "D2430", descripcion: "l\u00e1mina de oro - tres superficies" },
  { codigo: "D2510", descripcion: "Inlay - met\u00e1lica - una superficie" },
  { codigo: "D2520", descripcion: "Inlay - met\u00e1lica - dos superficies" },
  { codigo: "D2530", descripcion: "Inlay - met\u00e1lica - tres o m\u00e1s superficies" },
  { codigo: "D2542", descripcion: "onlay- met\u00e1licos - dos superficies" },
  { codigo: "D2543", descripcion: "onlay- met\u00e1lica - tres superficies" },
  { codigo: "D2544", descripcion: "onlay- met\u00e1lico - cuatro o m\u00e1s superficies" },
  { codigo: "D2610", descripcion: "inscrustaci\u00f3n- porcelana / cer\u00e1mica - una superficie" },
  { codigo: "D2620", descripcion: "incrustaci\u00f3n - porcelana / cer\u00e1mica - dos superficies" },
  { codigo: "D2630", descripcion: "incrustaci\u00f3n - porcelana / cer\u00e1mica - tres o m\u00e1s superficies" },
  { codigo: "D2642", descripcion: "onlay - porcelana / cer\u00e1mica - dos superficies" },
  { codigo: "D2643", descripcion: "onlay - porcelana / cer\u00e1mica - tres superficies" },
  { codigo: "D2644", descripcion: "onlay - porcelana / cer\u00e1mica - cuatro o m\u00e1s superficies" },
  { codigo: "D2650", descripcion: "Inlay - compuesto a base de resina - una superficie" },
  { codigo: "D2651", descripcion: "Inlay - compuesto a base de resina - dos superficies" },
  { codigo: "D2652", descripcion: "Inlay - compuesto a base de resina - tres o m\u00e1s superficies" },
  { codigo: "D2662", descripcion: "onlay - a base de resina compuesta - dos superficies" },
  { codigo: "D2663", descripcion: "onlay - a base de resina compuesta - tres superficies" },
  { codigo: "D2664", descripcion: "onlay - basado en compuestos - cuatro o m\u00e1s superficies de resina" },
  { codigo: "D2710", descripcion: "Corona - basado en resina compuesta (indirecta)" },
  { codigo: "D2712", descripcion: "Corona - 3.4 basado en resina compuesta (indirecta)" },
  { codigo: "D2720", descripcion: "Corona - resina con metal muy noble" },
  { codigo: "D2721", descripcion: "Corona - resina con metal predominantemente" },
  { codigo: "D2722", descripcion: "Corona - resina con metal noble" },
  { codigo: "D2740", descripcion: "Corona - porcelana / sustrato cer\u00e1mico" },
  { codigo: "D2750", descripcion: "Corona - porcelana fundida sobre metal muy noble" },
  { codigo: "D2751", descripcion: "Corona - porcelana fundida sobre metal com\u00fan predominantemente" },
  { codigo: "D2752", descripcion: "Corona - porcelana fundida sobre metal noble" },
  { codigo: "D2780", descripcion: "Corona - 3 / 4 fundido de metales nobles de alto" },
  { codigo: "D2781", descripcion: "Corona - 3 / 4 fundido de metal base predominantemente" },
  { codigo: "D2782", descripcion: "Corona - 3 / 4 fundido de metales nobles" },
  { codigo: "D2783", descripcion: "Corona - 3 / 4 de porcelana / cer\u00e1mica" },
  { codigo: "D2790", descripcion: "Corona - elenco completo de metales nobles de alto" },
  { codigo: "D2791", descripcion: "Corona - elenco completo de metal base predominantemente" },
  { codigo: "D2792", descripcion: "Corona - elenco completo de metales nobles" },
  { codigo: "D2794", descripcion: "Corona - titanio" },
  { codigo: "D2799", descripcion: "Corona provisional" },
  { codigo: "D2910", descripcion: "Recementaci\u00f3n incrustaciones onlay, restauraci\u00f3n o la cobertura parcial" },
  { codigo: "D2915", descripcion: "Recementaci\u00f3n, colados o prefabricados posterior y el n\u00facleo" },
  { codigo: "D2920", descripcion: "Corona Recementaci\u00f3n" },
  { codigo: "D2930", descripcion: "prefabricados corona de acero inoxidable - dientes primarios" },
  { codigo: "D2931", descripcion: "Corona de acero inoxidable prefabricados - diente permanente" },
  { codigo: "D2932", descripcion: "Corona de resina prefabricada" },
  { codigo: "D2933", descripcion: "Corona de acero inoxidable prefabricada con ventana de resina" },
  { codigo: "D2934", descripcion: "prefabricados est\u00e9tica inoxidable corona de acero recubiertos - diente primario" },
  { codigo: "D2940", descripcion: "llenado con sellantes" },
  { codigo: "D2950", descripcion: "acumulaci\u00f3n b\u00e1sico, incluidos los pines" },
  { codigo: "D2951", descripcion: "clavija de retenci\u00f3n - por diente, adem\u00e1s de la restauraci\u00f3n" },
  { codigo: "D2952", descripcion: "post y el n\u00facleo, adem\u00e1s de la corona, de manera indirecta fabricado" },
  { codigo: "D2953", descripcion: "indirecta fabricados despu\u00e9s de cada adicional- mismo diente" },
  { codigo: "D2954", descripcion: "prefabricados post y el n\u00facleo, adem\u00e1s de la corona" },
  { codigo: "D2955", descripcion: "eliminaci\u00f3n despu\u00e9s (y no en relaci\u00f3n con el tratamiento de endodoncia)" },
  { codigo: "D2957", descripcion: "prefabricados cada puesto adicional - el mismo diente" },
  { codigo: "D2960", descripcion: "labial chapa (laminado de resina) - sill\u00f3n" },
  { codigo: "D2961", descripcion: "chapa labial (laminado de resina) - El laboratorio" },
  { codigo: "D2962", descripcion: "labial chapas (laminados de porcelana) - El laboratorio" },
  { codigo: "D2970", descripcion: "temporal corona (diente fracturado)" },
  { codigo: "D2971", descripcion: "procedimientos adicionales para la construcci\u00f3n de una nueva corona en estructura de la pr\u00f3tesis parcial existente" },
  { codigo: "D2975", descripcion: "afrontamiento" },
  { codigo: "D2980", descripcion: "reparaci\u00f3n de la corona, en el informe" },
  { codigo: "D2999", descripcion: "sin especificar procedimiento de restauraci\u00f3n, en el informe" },
  { codigo: "D3110", descripcion: "recubrimiento pulpar - directa (excluyendo la reconstrucci\u00f3n final)" },
  { codigo: "D3120", descripcion: "recubrimiento pulpar - indirectos (excluyendo la reconstrucci\u00f3n final)" },
  { codigo: "D3220", descripcion: "pulpotom\u00eda terap\u00e9utica (excluyendo la reconstrucci\u00f3n final) - retirada de la pulpa coronal a la dentinocemental uni\u00f3n y la aplicaci\u00f3n de la medicaci\u00f3n" },
  { codigo: "D3221", descripcion: "pulpar, desbridamiento los dientes primarios y permanentes" },
  { codigo: "D3222", descripcion: "pulpotom\u00eda parcial para apexog\u00e9nesis - diente permanente con el desarrollo radicular incompleta" },
  { codigo: "D3230", descripcion: "pulpar terapia (reabsorbible llenado) - anterior, diente primario (excluyendo la reconstrucci\u00f3n final)" },
  { codigo: "D3240", descripcion: "pulpar terapia (reabsorbible llenado) - posterior, diente primario (excluyendo la reconstrucci\u00f3n final)" },
  { codigo: "D3310", descripcion: "endodoncia terapia, diente anterior (excluyendo la reconstrucci\u00f3n final)" },
  { codigo: "D3320", descripcion: "terapia endod\u00f3ntica, diente bic\u00faspide (excluyendo la reconstrucci\u00f3n final)" },
  { codigo: "D3330", descripcion: "endodoncia terapia, molar (excluyendo la reconstrucci\u00f3n final)" },
  { codigo: "D3331", descripcion: "tratamiento de la obstrucci\u00f3n del conducto radicular; quir\u00fargico acceso no" },
  { codigo: "D3332", descripcion: "incompleta terapia endod\u00f3ntica;, sin posibilidad de restauraci\u00f3n del diente fracturado o inoperables" },
  { codigo: "D3333", descripcion: "perforaci\u00f3n internas de reparaci\u00f3n de defectos de ra\u00edz" },
  { codigo: "D3346", descripcion: "retratamiento de tratamiento de conducto anterior - anterior" },
  { codigo: "D3347", descripcion: "retratamiento de tratamiento de conducto anterior - bic\u00faspide" },
  { codigo: "D3348", descripcion: "retratamiento de tratamiento de conducto anterior - molar" },
  { codigo: "D3351", descripcion: "apicoformaci\u00f3n / recalcificaci\u00f3n - visita inicial (cierre apical / reparaci\u00f3n c\u00e1lcica de perforaciones, la ra\u00edz reabsorci\u00f3n, etc)" },
  { codigo: "D3352", descripcion: "apicoformaci\u00f3n / recalcificaci\u00f3n - sustituci\u00f3n de medicamentos provisional (cierre apical / reparaci\u00f3n c\u00e1lcica de perforaciones, reabsorci\u00f3n radicular, etc" },
  { codigo: "D3353", descripcion: "apicoformaci\u00f3n/ recalcificaci\u00f3n - visita final (incluye completado la terapia del canal radicular \u2013 apical cierre o reparaci\u00f3n c\u00e1lcica de perforaciones, reabsorci\u00f3n radicular, etc)" },
  { codigo: "D3410", descripcion: "apicectom\u00eda/ cirug\u00eda perirradicular - anterior" },
  { codigo: "D3421", descripcion: "Apicectom\u00eda / cirug\u00eda perirradicular - bic\u00faspide (primera ra\u00edz)" },
  { codigo: "D3425", descripcion: "Apicectom\u00eda / cirug\u00eda perirradicular - molar (primera ra\u00edz)" },
  { codigo: "D3426", descripcion: "Apicectom\u00eda / cirug\u00eda perirradicular (cada ra\u00edz adicional)" },
  { codigo: "D3430", descripcion: "obturaci\u00f3n retr\u00f3grada - por ra\u00edz" },
  { codigo: "D3450", descripcion: "amputaci\u00f3n radicular - por ra\u00edz" },
  { codigo: "D3460", descripcion: "implante endod\u00f3ntico endo\u00f3seo" },
  { codigo: "D3470", descripcion: "reimplante intencional (incluyendo ferulizaci\u00f3n es necesario)" },
  { codigo: "D3910", descripcion: "procedimiento quir\u00fargico para el aislamiento del diente con dique de goma" },
  { codigo: "D3920", descripcion: "hemisecci\u00f3n (incluyendo cualquier extracci\u00f3n de ra\u00edz), sin incluir la terapia de conducto radicular" },
  { codigo: "D3950", descripcion: "preparaci\u00f3n del conducto y la instalaci\u00f3n de pasador preformado o post" },
  { codigo: "D3999", descripcion: "sin especificar procedimiento de endodoncia, el informe" },
  { codigo: "D4210", descripcion: "gingivectom\u00eda o gingivoplastia - cuatro o m\u00e1s dientes contiguos o un diente delimitadas espacios por cuadrante." },
  { codigo: "D4211", descripcion: "gingivectom\u00eda o gingivoplastia - uno a tres dientes contiguos o un diente delimitadas espacios por cuadrante." },
  { codigo: "D4230", descripcion: "exposici\u00f3n corona anat\u00f3mica - cuatro o m\u00e1s dientes contiguos por cuadrante" },
  { codigo: "D4231", descripcion: "exposici\u00f3n corona anat\u00f3mica - uno a tres dientes por cuadrante" },
  { codigo: "D4240", descripcion: "Procedimiento de colgajo gingival, incluyendo alisado radicular - cuatro o m\u00e1s dientes o dientes contiguos espacios delimitados por cuadrante" },
  { codigo: "D4241", descripcion: "Procedimiento de colgajo gingival, incluyendo alisado radicular - uno a tres dientes contiguos o un diente espacios delimitados por cuadrante" },
  { codigo: "D4245", descripcion: "apical colgajo" },
  { codigo: "D4249", descripcion: "alargamiento de corona cl\u00ednica - los tejidos duros" },
  { codigo: "D4260", descripcion: "\u00f3sea cirug\u00eda (incluyendo la entrada y el cierre del colgajo) - cuatro o m\u00e1s dientes o dientes contiguos espacios delimitados por cuadrante" },
  { codigo: "D4261", descripcion: "cirug\u00eda \u00f3sea (incluida la inscripci\u00f3n y el cierre del colgajo) - uno a tres dientes contiguos o un diente espacios delimitados por cuadrante" },
  { codigo: "D4263", descripcion: "de injerto \u00f3seo de reemplazo - primer sitio en el cuadrante" },
  { codigo: "D4264", descripcion: "sustituci\u00f3n del injerto \u00f3seo - cada sitio adicional en el cuadrante" },
  { codigo: "D4265", descripcion: "materiales biol\u00f3gicos para ayudar en la regeneraci\u00f3n de tejidos \u00f3seos y blandos" },
  { codigo: "D4266", descripcion: "regeneraci\u00f3n tisular guiada - barrera reabsorbible, el sitio por" },
  { codigo: "D4267", descripcion: "la regeneraci\u00f3n tisular guiada - barrera no reabsorbible, sitio por (incluye retiro de la membrana)" },
  { codigo: "D4268", descripcion: "procedimiento de revisi\u00f3n quir\u00fargica, por diente" },
  { codigo: "D4270", descripcion: "ped\u00edculo de tejido blando del procedimiento de injerto" },
  { codigo: "D4271", descripcion: "libre tejidos blandos del procedimiento de injerto (incluyendo sitio de la cirug\u00eda del donante)" },
  { codigo: "D4273", descripcion: "injerto subepitelial del tejido procedimientos, por diente" },
  { codigo: "D4274", descripcion: "o proximal distal procedimiento de cu\u00f1a (cuando no se realiza conjuntamente con cirug\u00eda procedimientos en la misma \u00e1rea anat\u00f3mica)" },
  { codigo: "D4275", descripcion: "injerto de tejido blando" },
  { codigo: "D4276", descripcion: "combinadas del tejido conectivo y el doble injerto pediculado, por diente" },
  { codigo: "D4320", descripcion: "provisional ferulizaci\u00f3n - intracoronales" },
  { codigo: "D4321", descripcion: "f\u00e9rula provisional - extracoronal" },
  { codigo: "D4341", descripcion: "escalamiento periodontal y alisado radicular - cuatro o m\u00e1s dientes por cuadrante" },
  { codigo: "D4342", descripcion: "escalamiento periodontal y alisado radicular - uno a tres dientes por cuadrante" },
  { codigo: "D4355", descripcion: "desbridamiento para permitir una evaluaci\u00f3n integral y el diagn\u00f3stico" },
  { codigo: "D4381", descripcion: "distribuci\u00f3n localizada de los agentes antimicrobianos a trav\u00e9s de un veh\u00edculo de liberaci\u00f3n controlada en enfermos tejido crevicular, por diente, por el informe" },
  { codigo: "D4910", descripcion: "mantenimiento periodontal" },
  { codigo: "D4920", descripcion: "imprevisto cambio de ap\u00f3sito (por alguien que no sea el tratamiento de dentista)" },
  { codigo: "D4999", descripcion: "sin especificar procedimiento periodontal, por el informe" },
  { codigo: "D5110", descripcion: "pr\u00f3tesis completa - maxilar" },
  { codigo: "D5120", descripcion: "pr\u00f3tesis completa - mandibular" },
  { codigo: "D5130", descripcion: "pr\u00f3tesis inmediata - maxilar" },
  { codigo: "D5140", descripcion: "pr\u00f3tesis inmediata - mandibular" },
  { codigo: "D5211", descripcion: "pr\u00f3tesis parcial maxilar - base de resina (incluye cualquier gancho convencional, descansa y dientes)" },
  { codigo: "D5212", descripcion: "pr\u00f3tesis parcial mandibular - base de resina (incluye cualquier gancho convencional, descansa y dientes" },
  { codigo: "D5213", descripcion: "pr\u00f3tesis parcial maxilar - armaz\u00f3n de metal fundido con bases de resina (incluyendo cualquier cierres convencionales, descansa y dientes)" },
  { codigo: "D5214", descripcion: "pr\u00f3tesis parcial mandibular - armaz\u00f3n colado de metal con bases de resina (incluyendo cualquier cierres convencionales, descansa y dientes)" },
  { codigo: "D5225", descripcion: "pr\u00f3tesis parcial maxilar - base flexible (incluyendo cualquier gancho, descansa y dientes)" },
  { codigo: "D5226", descripcion: "mandibular pr\u00f3tesis parcial - base flexible (incluyendo cualquier gancho, descansa y dientes)" },
  { codigo: "D5281", descripcion: "pr\u00f3tesis parcial removible unilateral - una pieza de metal fundido (incluidos los cierres y los dientes)" },
  { codigo: "D5410", descripcion: "ajustar pr\u00f3tesis completa - maxilar" },
  { codigo: "D5411", descripcion: "ajustar pr\u00f3tesis completa - mandibular" },
  { codigo: "D5421", descripcion: "ajustar la pr\u00f3tesis parcial - maxilar" },
  { codigo: "D5422", descripcion: "ajustar la pr\u00f3tesis parcial - mandibular" },
  { codigo: "D5510", descripcion: "reparaci\u00f3n de rotos base de la pr\u00f3tesis completa" },
  { codigo: "D5520", descripcion: "reemplazar los faltantes o dientes rotos - pr\u00f3tesis completa (cada diente)" },
  { codigo: "D5610", descripcion: "reparaci\u00f3n base de resina" },
  { codigo: "D5620", descripcion: "reparaci\u00f3n de colado" },
  { codigo: "D5630", descripcion: "reparar o reemplazar broche roto" },
  { codigo: "D5640", descripcion: "reemplazar dientes rotos - por diente" },
  { codigo: "D5650", descripcion: "a\u00f1adir diente para pr\u00f3tesis parcial existente" },
  { codigo: "D5660", descripcion: "a\u00f1adir broche a pr\u00f3tesis parcial existente" },
  { codigo: "D5670", descripcion: "reemplazar todos los dientes de metal y acr\u00edlico sobre armaz\u00f3n colado (maxilar)" },
  { codigo: "D5671", descripcion: "reemplazar todos los dientes de metal y acr\u00edlico sobre armaz\u00f3n colado (mandibular)" },
  { codigo: "D5710", descripcion: "rebase pr\u00f3tesis completa superior" },
  { codigo: "D5711", descripcion: "rebase pr\u00f3tesis mandibular completa" },
  { codigo: "D5720", descripcion: "rebase la pr\u00f3tesis parcial superior" },
  { codigo: "D5721", descripcion: "rebase pr\u00f3tesis parcial inferior" },
  { codigo: "D5730", descripcion: "rectificaci\u00f3n pr\u00f3tesis superior completa (sill\u00f3n)" },
  { codigo: "D5731", descripcion: "rectificaci\u00f3n dentadura mandibular completa (sill\u00f3n)" },
  { codigo: "D5740", descripcion: "rectificaci\u00f3n maxilar pr\u00f3tesis parcial (sill\u00f3n)" },
  { codigo: "D5741", descripcion: "rectificaci\u00f3n pr\u00f3tesis parcial inferior (sill\u00f3n)" },
  { codigo: "D5750", descripcion: "rectificaci\u00f3n pr\u00f3tesis superior completa (laboratorio)" },
  { codigo: "D5751", descripcion: "rectificaci\u00f3n dentadura mandibular completa (laboratorio)" },
  { codigo: "D5760", descripcion: "rectificaci\u00f3n maxilar pr\u00f3tesis parcial (laboratorio)" },
  { codigo: "D5761", descripcion: "rectificaci\u00f3n pr\u00f3tesis parcial inferior (laboratorio)" },
  { codigo: "D5810", descripcion: "provisionales pr\u00f3tesis completa (superior)" },
  { codigo: "D5811", descripcion: "completa pr\u00f3tesis provisionales (mandibular)" },
  { codigo: "D5820", descripcion: "provisionales pr\u00f3tesis parcial (maxilar)" },
  { codigo: "D5821", descripcion: "pr\u00f3tesis parcial provisional (mandibular)" },
  { codigo: "D5850", descripcion: "acondicionamiento de los tejidos, maxilar" },
  { codigo: "D5851", descripcion: "tejido acondicionado, mandibular" },
  { codigo: "D5860", descripcion: "sobredentadura - completo, en el informe" },
  { codigo: "D5861", descripcion: "sobredentadura - parcial, en el informe" },
  { codigo: "D5862", descripcion: "accesorio de precisi\u00f3n, por el informe" },
  { codigo: "D5867", descripcion: "reemplazo de una pieza sustituible de semi-precisi\u00f3n o accesorio de precisi\u00f3n (hombre o mujer componente)" },
  { codigo: "D5875", descripcion: "modificaci\u00f3n de pr\u00f3tesis removibles despu\u00e9s de la cirug\u00eda de implantes" },
  { codigo: "D5899", descripcion: "sin especificar pr\u00f3tesis removible procedimiento, en el informe" },
  { codigo: "D5911", descripcion: "moulage facial (secci\u00f3n)" },
  { codigo: "D5912", descripcion: "(completo) faciales moulage" },
  { codigo: "D5913", descripcion: "pr\u00f3tesis nasal" },
  { codigo: "D5914", descripcion: "pr\u00f3tesis auricular" },
  { codigo: "D5915", descripcion: "orbital pr\u00f3tesis" },
  { codigo: "D5916", descripcion: "pr\u00f3tesis oculares" },
  { codigo: "D5919", descripcion: "pr\u00f3tesis faciales" },
  { codigo: "D5922", descripcion: "pr\u00f3tesis del tabique nasal" },
  { codigo: "D5923", descripcion: "pr\u00f3tesis oculares, con car\u00e1cter interino" },
  { codigo: "D5924", descripcion: "pr\u00f3tesis craneal" },
  { codigo: "D5925", descripcion: "aumento facial pr\u00f3tesis sobre implantes" },
  { codigo: "D5926", descripcion: "nasal pr\u00f3tesis, la sustituci\u00f3n" },
  { codigo: "D5927", descripcion: "pr\u00f3tesis auricular, la sustituci\u00f3n" },
  { codigo: "D5928", descripcion: "pr\u00f3tesis orbital, la sustituci\u00f3n" },
  { codigo: "D5929", descripcion: "faciales pr\u00f3tesis, la sustituci\u00f3n" },
  { codigo: "D5931", descripcion: "obturador pr\u00f3tesis, cirug\u00eda" },
  { codigo: "D5932", descripcion: "pr\u00f3tesis obturatriz, definitiva" },
  { codigo: "D5933", descripcion: "pr\u00f3tesis obturatriz, modificaci\u00f3n" },
  { codigo: "D5934", descripcion: "pr\u00f3tesis de resecci\u00f3n mandibular con brida gu\u00eda" },
  { codigo: "D5935", descripcion: "pr\u00f3tesis mandibular resecci\u00f3n sin brida de la gu\u00eda" },
  { codigo: "D5936", descripcion: "pr\u00f3tesis obturatriz, con car\u00e1cter interino" },
  { codigo: "D5937", descripcion: "abrebocas de goma (no para el tratamiento de TTM)" },
  { codigo: "D5951", descripcion: "alimentaci\u00f3n de las ayudas" },
  { codigo: "D5952", descripcion: "discursor pr\u00f3tesis ayuda, pedi\u00e1trica" },
  { codigo: "D5953", descripcion: "discursor pr\u00f3tesis ayuda de un adulto" },
  { codigo: "D5954", descripcion: "pr\u00f3tesis de aumento del paladar" },
  { codigo: "D5955", descripcion: "pr\u00f3tesis elevaci\u00f3n del paladar, definitiva" },
  { codigo: "D5958", descripcion: "pr\u00f3tesis elevaci\u00f3n del paladar, con car\u00e1cter interino" },
  { codigo: "D5959", descripcion: "pr\u00f3tesis elevaci\u00f3n del paladar, la modificaci\u00f3n" },
  { codigo: "D5960", descripcion: "discursor ayudas de pr\u00f3tesis, la modificaci\u00f3n" },
  { codigo: "D5982", descripcion: "ap\u00f3sito quir\u00fargico" },
  { codigo: "D5983", descripcion: "compa\u00f1\u00eda de radiaci\u00f3n" },
  { codigo: "D5984", descripcion: "escudo contra la radiaci\u00f3n" },
  { codigo: "D5985", descripcion: "radiaci\u00f3n cono localizador" },
  { codigo: "D5986", descripcion: "de soporte del gel de fl\u00faor" },
  { codigo: "D5987", descripcion: "comisura f\u00e9rula" },
  { codigo: "D5988", descripcion: "f\u00e9rula quir\u00fargica" },
  { codigo: "D5991", descripcion: "compa\u00f1\u00eda medicamento t\u00f3pico" },
  { codigo: "D5999", descripcion: "sin especificar pr\u00f3tesis maxilofacial, en el informe" },
  { codigo: "D6010", descripcion: "quir\u00fargica de colocaci\u00f3n del cuerpo del implante: implante endo\u00f3seo" },
  { codigo: "D6012", descripcion: "la colocaci\u00f3n quir\u00fargica de implantes \u00f3rgano provisional para pr\u00f3tesis de transici\u00f3n: implante endo\u00f3seo" },
  { codigo: "D6040", descripcion: "colocaci\u00f3n quir\u00fargica de implante eposteal" },
  { codigo: "D6050", descripcion: "colocaci\u00f3n quir\u00fargica de implante trans\u00f3seo" },
  { codigo: "D6053", descripcion: "implante / pilar apoyado pr\u00f3tesis removible para desdentados arco completo" },
  { codigo: "D6054", descripcion: "implante / pilar apoyado pr\u00f3tesis removible para desdentados arcada parcialmente" },
  { codigo: "D6055", descripcion: "implantes dentales apoyado la barra de conexi\u00f3n" },
  { codigo: "D6056", descripcion: "prefabricados pilar - incluye la colocaci\u00f3n" },
  { codigo: "D6057", descripcion: "Colocar las piezas en - incluye la colocaci\u00f3n" },
  { codigo: "D6058", descripcion: "pilar apoyado porcelana / corona de cer\u00e1mica" },
  { codigo: "D6059", descripcion: "pilar apoyo a la corona de porcelana fundida sobre metal (metal noble de alto)" },
  { codigo: "D6060", descripcion: "pilar apoyo a la corona de porcelana fundida sobre metal (metal predominantemente)" },
  { codigo: "D6061", descripcion: "pilar apoyo a la corona de porcelana fundida sobre metal (metal noble)" },
  { codigo: "D6062", descripcion: "pilar apoyo corona de metal fundido (metal noble de alto)" },
  { codigo: "D6063", descripcion: "pilar apoyo corona de metal fundido (metal predominantemente)" },
  { codigo: "D6064", descripcion: "pilar apoyo corona de metal fundido (metal noble)" },
  { codigo: "D6065", descripcion: "implantosoportado porcelana / corona de cer\u00e1mica" },
  { codigo: "D6066", descripcion: "implante apoyo porcelana fundida sobre corona de metal (titanio, aleaci\u00f3n de titanio, noble de alto metal" },
  { codigo: "D6067", descripcion: "implante met\u00e1lico apoyado corona (de titanio, aleaci\u00f3n de titanio, metal muy noble)" },
  { codigo: "D6068", descripcion: "pilar apoyo de retenci\u00f3n para la porcelana / cer\u00e1mica FPD" },
  { codigo: "D6069", descripcion: "pilar apoyo de retenci\u00f3n para la porcelana fundida sobre metal FPD (metal noble de alto)" },
  { codigo: "D6070", descripcion: "pilar apoyo de retenci\u00f3n para la porcelana fundida sobre metal FPD (base de metal predominantemente)" },
  { codigo: "D6071", descripcion: "pilar apoyo de retenci\u00f3n para la porcelana fundida sobre metal FPD (metal noble)" },
  { codigo: "D6072", descripcion: "pilar apoyo de retenci\u00f3n para el metal fundido FPD (metal noble de alto)" },
  { codigo: "D6073", descripcion: "pilar apoyo de retenci\u00f3n para el metal fundido FPD (base de metal predominantemente)" },
  { codigo: "D6074", descripcion: "pilar apoyo de retenci\u00f3n para el metal fundido FPD (metal noble)" },
  { codigo: "D6075", descripcion: "implante apoyo de retenci\u00f3n de cer\u00e1mica FPD" },
  { codigo: "D6076", descripcion: "implante apoyo de retenci\u00f3n para la porcelana fundida sobre metal FPD (titanio, aleaciones de titanio de metales nobles)" },
  { codigo: "D6077", descripcion: "apoyo de retenci\u00f3n del implante de metal fundido FPD (titanio, aleaci\u00f3n de titanio, o de metales nobles)" },
  { codigo: "D6078", descripcion: "implante / pilar apoyado pr\u00f3tesis fija para desdentados arco completo" },
  { codigo: "D6079", descripcion: "implante / pilar apoyado pr\u00f3tesis fija de arcada parcialmente ed\u00e9ntula" },
  { codigo: "D6080", descripcion: "mantenimiento de los procedimientos de implantes, incluyendo la remoci\u00f3n de la pr\u00f3tesis, la limpieza de pr\u00f3tesis y los pilares y la reinserci\u00f3n de pr\u00f3tesis" },
  { codigo: "D6090", descripcion: "reparaci\u00f3n de pr\u00f3tesis de implantes" },
  { codigo: "D6091", descripcion: "sustituci\u00f3n de semi-precisi\u00f3n o accesorio de precisi\u00f3n (hombre o mujer de componentes) de implante / pilar apoyado pr\u00f3tesis, por archivo adjunto" },
  { codigo: "D6092", descripcion: "implante Recementaci\u00f3n / pilar apoyado corona" },
  { codigo: "D6093", descripcion: "implante Recementaci\u00f3n / pilar apoyado pr\u00f3tesis parcial fija" },
  { codigo: "D6094", descripcion: "pilar apoyo corona - (titanio)" },
  { codigo: "D6095", descripcion: "reparaci\u00f3n pilar del implante" },
  { codigo: "D6100", descripcion: "Extracci\u00f3n del implante" },
  { codigo: "D6190", descripcion: "radiograf\u00eda / \u00edndice de implante quir\u00fargico" },
  { codigo: "D6194", descripcion: "pilar apoyo corona de retenci\u00f3n para FPD - (titanio)" },
  { codigo: "D6199", descripcion: "procedimiento de implante no se especifica, en el informe" },
  { codigo: "D6205", descripcion: "p\u00f3ntico - resina compuesta indirecta por raz\u00f3n" },
  { codigo: "D6210", descripcion: "p\u00f3ntico fundido de metales nobles de alto" },
  { codigo: "D6211", descripcion: "p\u00f3ntico - base de metal fundido predominantemente" },
  { codigo: "D6212", descripcion: "p\u00f3ntico - fundido de metales nobles" },
  { codigo: "D6214", descripcion: "p\u00f3ntico - titanio" },
  { codigo: "D6240", descripcion: "p\u00f3ntico - porcelana fundida sobre metal muy noble" },
  { codigo: "D6241", descripcion: "p\u00f3ntico - porcelana fundida sobre metal com\u00fan predominantemente" },
  { codigo: "D6242", descripcion: "p\u00f3ntico porcelana fundida sobre metal noble" },
  { codigo: "D6245", descripcion: "p\u00f3ntico - porcelana / cer\u00e1mica" },
  { codigo: "D6250", descripcion: "p\u00f3ntico resina con metal muy noble" },
  { codigo: "D6251", descripcion: "p\u00f3ntico - resina con metal predominantemente" },
  { codigo: "D6252", descripcion: "p\u00f3ntico resina con metal noble" },
  { codigo: "D6253", descripcion: "provisional p\u00f3ntico" },
  { codigo: "D6545", descripcion: "retenedor - metal fundido de la resina en condiciones de servidumbre pr\u00f3tesis fija" },
  { codigo: "D6548", descripcion: "retenedor - porcelana / cer\u00e1mica para la resina de pr\u00f3tesis fija en condiciones de servidumbre" },
  { codigo: "D6600", descripcion: "incrustaci\u00f3n- porcelana / cer\u00e1mica, dos superficies" },
  { codigo: "D6601", descripcion: "Inlay - porcelana / cer\u00e1mica, tres o m\u00e1s superficies" },
  { codigo: "D6602", descripcion: "Inlay - fundido de metales nobles de alto, dos superficies" },
  { codigo: "D6603", descripcion: "Inlay - fundido de metales nobles de alto, tres o m\u00e1s superficies" },
  { codigo: "D6604", descripcion: "Inlay - base de metal fundido sobre todo, dos superficies" },
  { codigo: "D6605", descripcion: "incrustaci\u00f3n - base de metal fundido sobre todo, tres o m\u00e1s superficies" },
  { codigo: "D6606", descripcion: "incrustaci\u00f3n - fundido de metales nobles, dos superficies" },
  { codigo: "D6607", descripcion: "Inlay - metal colado noble, tres o m\u00e1s superficies" },
  { codigo: "D6608", descripcion: "onlay - porcelana / cer\u00e1mica, dos superficies" },
  { codigo: "D6609", descripcion: "onlay - porcelana / cer\u00e1mica, tres o m\u00e1s superficies" },
  { codigo: "D6610", descripcion: "onlay - fundido de metales nobles de alto, dos superficies" },
  { codigo: "D6611", descripcion: "onlay - fundido de metales nobles de alto, tres o m\u00e1s superficies" },
  { codigo: "D6612", descripcion: "onlay - base de metal fundido sobre todo, dos superficies" },
  { codigo: "D6613", descripcion: "onlay - base de metal fundido sobre todo, tres o m\u00e1s superficies" },
  { codigo: "D6614", descripcion: "onlay - fundido de metales nobles, dos superficies" },
  { codigo: "D6615", descripcion: "onlay - fundido de metales nobles, tres o m\u00e1s superficies" },
  { codigo: "D6624", descripcion: "Inlay - titanio" },
  { codigo: "D6634", descripcion: "onlay - titanio" },
  { codigo: "D6710", descripcion: "Corona - resina compuesta indirecta por raz\u00f3n" },
  { codigo: "D6720", descripcion: "Corona - resina con metal muy noble" },
  { codigo: "D6721", descripcion: "Corona - resina con metal predominantemente" },
  { codigo: "D6722", descripcion: "Corona - resina con metal noble" },
  { codigo: "D6740", descripcion: "Corona - porcelana / cer\u00e1mica" },
  { codigo: "D6750", descripcion: "Corona - porcelana fundida sobre metal muy noble" },
  { codigo: "D6751", descripcion: "Corona - porcelana fundida sobre metal com\u00fan predominantemente" },
  { codigo: "D6752", descripcion: "Corona - porcelana fundida sobre metal noble" },
  { codigo: "D6780", descripcion: "Corona - 3 / 4 fundido de metales nobles de alto" },
  { codigo: "D6781", descripcion: "Corona - 3 / 4 fundido de metal base predominantemente" },
  { codigo: "D6782", descripcion: "Corona - 3 / 4 fundido de metales nobles" },
  { codigo: "D6783", descripcion: "Corona - 3 / 4 de porcelana / cer\u00e1mica" },
  { codigo: "D6790", descripcion: "Corona - elenco completo de metales nobles de alto" },
  { codigo: "D6791", descripcion: "Corona - elenco completo de metal base predominantemente" },
  { codigo: "D6792", descripcion: "Corona - elenco completo de metales nobles" },
  { codigo: "D6793", descripcion: "corona provisional de retenci\u00f3n" },
  { codigo: "D6794", descripcion: "Corona - titanio" },
  { codigo: "D6920", descripcion: "barra de conexi\u00f3n" },
  { codigo: "D6930", descripcion: "recementaci\u00f3n pr\u00f3tesis parcial fija" },
  { codigo: "D6940", descripcion: "rompefuerzas" },
  { codigo: "D6950", descripcion: "accesorio de precisi\u00f3n" },
  { codigo: "D6970", descripcion: "posterior y el n\u00facleo, adem\u00e1s de parcial de retenci\u00f3n de pr\u00f3tesis fijas, de manera indirecta fabricado" },
  { codigo: "D6972", descripcion: "prefabricados post y el n\u00facleo, adem\u00e1s de retenci\u00f3n parcial pr\u00f3tesis fija" },
  { codigo: "D6973", descripcion: "reconstrucci\u00f3n de mu\u00f1ones para retenedor, incluidos los apoyos" },
  { codigo: "D6975", descripcion: "afrontamiento - metal" },
  { codigo: "D6976", descripcion: "cada adicional fabricado indirectamente post - mismo diente" },
  { codigo: "D6977", descripcion: "prefabricados cada puesto adicional - el mismo diente" },
  { codigo: "D6980", descripcion: "fijo de reparaci\u00f3n de pr\u00f3tesis parciales, en el informe" },
  { codigo: "D6985", descripcion: "pedi\u00e1trica pr\u00f3tesis parcial, fijo" },
  { codigo: "D6999", descripcion: "sin especificar prostod\u00f3ncico procedimiento fijo, por el informe" },
  { codigo: "D7111", descripcion: "Extracci\u00f3n, remanentes coronal - diente temporal" },
  { codigo: "D7140", descripcion: "extracci\u00f3n del diente o ra\u00edz expuesta" },
  { codigo: "D7210", descripcion: "Extracci\u00f3n quir\u00fargica de diente erupcionado que requieren la elevaci\u00f3n del colgajo mucoperi\u00f3stico y la extracci\u00f3n \u00f3sea y / o secci\u00f3n de un diente" },
  { codigo: "D7220", descripcion: "Extracci\u00f3n de diente impactado - los tejidos blandos" },
  { codigo: "D7230", descripcion: "Extracci\u00f3n de diente impactado - parcialmente \u00f3seo" },
  { codigo: "D7240", descripcion: "Extracci\u00f3n de diente impactado - completamente \u00f3seo" },
  { codigo: "D7241", descripcion: "Extracci\u00f3n de diente impactado - completamente \u00f3seo, con inusual complicaciones quir\u00fargicas" },
  { codigo: "D7250", descripcion: "Extracci\u00f3n quir\u00fargica de ra\u00edces de los dientes residuales (procedimiento de corte)" },
  { codigo: "D7260", descripcion: "cierre de la f\u00edstula oroantrales" },
  { codigo: "D7261", descripcion: "cierre primario de una perforaci\u00f3n del seno" },
  { codigo: "D7270", descripcion: "reimplante del diente y / o estabilizaci\u00f3n de forma accidental o desplazados avulseonado." },
  { codigo: "D7272", descripcion: "trasplante de dientes (incluye reimplante de un sitio a otro y f\u00e9rulas y / o estabilizaci\u00f3n)" },
  { codigo: "D7280", descripcion: "acceso quir\u00fargico de un diente erupcionado" },
  { codigo: "D7282", descripcion: "movilizaci\u00f3n de erupci\u00f3n del diente o mal posicionados para ayudar a la erupci\u00f3n" },
  { codigo: "D7283", descripcion: "colocaci\u00f3n del dispositivo para facilitar la erupci\u00f3n del diente impactado" },
  { codigo: "D7285", descripcion: "biopsia de tejido oral - (hueso duro, diente)" },
  { codigo: "D7286", descripcion: "biopsia de tejido oral - suave" },
  { codigo: "D7287", descripcion: "citolog\u00eda exfoliativa recogida de muestras" },
  { codigo: "D7288", descripcion: "biopsia por cepillado - toma de muestra transepitelial" },
  { codigo: "D7290", descripcion: "reposicionamiento quir\u00fargico de los dientes" },
  { codigo: "D7291", descripcion: "fibrotom\u00eda transeptal / cresta fibrotom\u00eda supra, el informe" },
  { codigo: "D7292", descripcion: "colocaci\u00f3n quir\u00fargica: anclaje [dispositivo de husillo temporal conservaron] placa que requieren cirug\u00eda" },
  { codigo: "D7293", descripcion: "colocaci\u00f3n quir\u00fargica: dispositivo de anclaje temporal que requieren colgajo quir\u00fargico" },
  { codigo: "D7294", descripcion: "quir\u00fargica de colocaci\u00f3n: dispositivo de anclaje temporal sin colgajo quir\u00fargico" },
  { codigo: "D7310", descripcion: "alveoloplastia junto con extracciones - cuatro o m\u00e1s dientes o espacios dentales, por cuadrante" },
  { codigo: "D7311", descripcion: "alveoloplastia junto con extracciones - uno a tres dientes o espacios dentales, por cuadrante" },
  { codigo: "D7320", descripcion: "alveoloplastia no junto con extracciones - cuatro o m\u00e1s dientes o espacios dentales, por cuadrante." },
  { codigo: "D7321", descripcion: "alveoloplastia no junto con extracciones - uno a tres dientes o espacios dentales, por cuadrante" },
  { codigo: "D7340", descripcion: "vestibuloplastia - la extensi\u00f3n del reborde (epitelizaci\u00f3n secundaria)" },
  { codigo: "D7350", descripcion: "vestibuloplastia - la extensi\u00f3n del reborde (incluyendo los injertos de tejidos blandos, m\u00fasculos reinserci\u00f3n, revisi\u00f3n de los datos adjuntos de tejidos blandos y la gesti\u00f3n de hipertrofia y hiperplasia tejido)" },
  { codigo: "D7410", descripcion: "escisi\u00f3n de lesi\u00f3n benigna hasta 1,25 cm" },
  { codigo: "D7411", descripcion: "escisi\u00f3n de lesi\u00f3n benigna mayor de 1,25 cm" },
  { codigo: "D7412", descripcion: "escisi\u00f3n de lesi\u00f3n benigna, complicada" },
  { codigo: "D7413", descripcion: "escisi\u00f3n de lesi\u00f3n maligna de hasta 1,25 cm" },
  { codigo: "D7414", descripcion: "escisi\u00f3n de lesi\u00f3n maligna superior a 1,25 cm" },
  { codigo: "D7415", descripcion: "escisi\u00f3n de lesi\u00f3n maligna, complicado" },
  { codigo: "D7440", descripcion: "extirpaci\u00f3n de un tumor maligno - di\u00e1metro de la lesi\u00f3n hasta 1,25 cm" },
  { codigo: "D7441", descripcion: "extirpaci\u00f3n de un tumor maligno - di\u00e1metro de la lesi\u00f3n superior a 1,25 cm" },
  { codigo: "D7450", descripcion: "eliminaci\u00f3n de odontog\u00e9nico quiste benigno o un tumor - di\u00e1metro de la lesi\u00f3n hasta 1,25 cm" },
  { codigo: "D7451", descripcion: "eliminaci\u00f3n de odontog\u00e9nico quiste benigno o un tumor - di\u00e1metro de la lesi\u00f3n superior a 1,25 cm" },
  { codigo: "D7460", descripcion: "eliminaci\u00f3n de los no odontog\u00e9nico quiste benigno o un tumor - di\u00e1metro de la lesi\u00f3n hasta 1,25 cm" },
  { codigo: "D7461", descripcion: "eliminaci\u00f3n de los no odontog\u00e9nico quiste benigno o un tumor - di\u00e1metro de la lesi\u00f3n superior a 1,25 cm" },
  { codigo: "D7465", descripcion: "destrucci\u00f3n de la lesi\u00f3n (s) por el m\u00e9todo f\u00edsico o qu\u00edmico, en el informe" },
  { codigo: "D7471", descripcion: "eliminaci\u00f3n de exostosis lateral (maxilar o mand\u00edbula)" },
  { codigo: "D7472", descripcion: "eliminaci\u00f3n del torus palatino" },
  { codigo: "D7473", descripcion: "eliminaci\u00f3n de torus mandibular" },
  { codigo: "D7485", descripcion: "reducci\u00f3n quir\u00fargica de la tuberosidad \u00f3sea" },
  { codigo: "D7490", descripcion: "resecci\u00f3n radical del maxilar o la mand\u00edbula" },
  { codigo: "D7510", descripcion: "incisi\u00f3n y drenaje de absceso - tejido blando intraoral" },
  { codigo: "D7511", descripcion: "incisi\u00f3n y drenaje de absceso - tejido blando intrabucal - complicado (incluye drenaje de m\u00faltiples espacios faciales)" },
  { codigo: "D7520", descripcion: "incisi\u00f3n y drenaje de absceso - tejidos blandos extraorales" },
  { codigo: "D7521", descripcion: "incisi\u00f3n y drenaje de absceso - tejidos blandos extraorales - complicado (incluye drenaje de m\u00faltiples espacios faciales)" },
  { codigo: "D7530", descripcion: "extracci\u00f3n de cuerpo extra\u00f1o de la mucosa, la piel o tejido alveolar subcut\u00e1neo" },
  { codigo: "D7540", descripcion: "eliminaci\u00f3n de la reacci\u00f3n producir cuerpos extra\u00f1os, sistema musculoesquel\u00e9tico" },
  { codigo: "D7550", descripcion: "ostectom\u00eda parcial / secuestrectom\u00eda para la remoci\u00f3n de hueso no vital" },
  { codigo: "D7560", descripcion: "maxilar sinusotom\u00eda para la separaci\u00f3n de los fragmentos del diente o cuerpo extra\u00f1o" },
  { codigo: "D7610", descripcion: "reducci\u00f3n maxilar abierta (dientes de inmovilizado, si est\u00e1 presente)" },
  { codigo: "D7620", descripcion: "reducci\u00f3n maxilar cerrada (dientes de inmovilizado, si est\u00e1 presente)" },
  { codigo: "D7630", descripcion: "reducci\u00f3n mandibular abierta (dientes de inmovilizado, si est\u00e1 presente)" },
  { codigo: "D7640", descripcion: "reducci\u00f3n mandibular cerrada (dientes de inmovilizado, si est\u00e1 presente)" },
  { codigo: "D7650", descripcion: "malar y / o arco cigom\u00e1tico - reducci\u00f3n abierta" },
  { codigo: "D7660", descripcion: "malar y / o arco cigom\u00e1tico - la reducci\u00f3n cerrada" },
  { codigo: "D7670", descripcion: "reducci\u00f3n alveolar cerrada, puede incluir la estabilizaci\u00f3n de los dientes" },
  { codigo: "D7671", descripcion: "reducci\u00f3n alveolar abierta, puede incluir la estabilizaci\u00f3n de los dientes" },
  { codigo: "D7680", descripcion: "huesos faciales - la reducci\u00f3n de la fijaci\u00f3n y complicada con m\u00faltiples abordajes quir\u00fargicos" },
  { codigo: "D7710", descripcion: "reducci\u00f3n abierta de maxilar" },
  { codigo: "D7720", descripcion: "reducci\u00f3n cerrada de maxilar" },
  { codigo: "D7730", descripcion: "reducci\u00f3n abierta de mand\u00edbula" },
  { codigo: "D7740", descripcion: "reducci\u00f3n cerrada de mand\u00edbula" },
  { codigo: "D7750", descripcion: "malar y / o arco cigom\u00e1tico - reducci\u00f3n abierta" },
  { codigo: "D7760", descripcion: "malar y / o arco cigom\u00e1tico - la reducci\u00f3n cerrada" },
  { codigo: "D7770", descripcion: "estabilizaci\u00f3n del alveolo- reducci\u00f3n abierta de los dientes" },
  { codigo: "D7771", descripcion: "estabilizaci\u00f3n de alveolo- reducci\u00f3n cerrada de los dientes" },
  { codigo: "D7780", descripcion: "reducci\u00f3n y fijaci\u00f3n de los huesos faciales-complicada con m\u00faltiples abordajes quir\u00fargicos" },
  { codigo: "D7810", descripcion: "reducci\u00f3n abierta de la luxaci\u00f3n" },
  { codigo: "D7820", descripcion: "reducci\u00f3n cerrada de la luxaci\u00f3n" },
  { codigo: "D7830", descripcion: "manipulaci\u00f3n bajo anestesia" },
  { codigo: "D7840", descripcion: "condilectom\u00eda" },
  { codigo: "D7850", descripcion: "discectom\u00eda quir\u00fargica, con o sin implante" },
  { codigo: "D7852", descripcion: "reparaci\u00f3n de discos" },
  { codigo: "D7854", descripcion: "sinovectom\u00eda" },
  { codigo: "D7856", descripcion: "miotom\u00eda" },
  { codigo: "D7858", descripcion: "reconstrucci\u00f3n de articulaciones" },
  { codigo: "D7860", descripcion: "artrotom\u00eda" },
  { codigo: "D7865", descripcion: "artroplastia" },
  { codigo: "D7870", descripcion: "artrocentesis" },
  { codigo: "D7871", descripcion: "-lisis artrosc\u00f3pica con/sin lavado" },
  { codigo: "D7872", descripcion: "artroscopia - diagn\u00f3stico, con o sin biopsia" },
  { codigo: "D7873", descripcion: "artroscopia - quir\u00fargica: lavado y lisis de adherencias" },
  { codigo: "D7874", descripcion: "artroscopia - quir\u00fargico: disco de reposicionamiento y la estabilizaci\u00f3n" },
  { codigo: "D7875", descripcion: "artroscopia - quir\u00fargico: sinovectom\u00eda" },
  { codigo: "D7876", descripcion: "artroscopia - quir\u00fargico: discectom\u00eda" },
  { codigo: "D7877", descripcion: "artroscopia - quir\u00fargico: desbridamiento" },
  { codigo: "D7880", descripcion: "dispositivo ortop\u00e9dico oclusal, por informe" },
  { codigo: "D7899", descripcion: "sin especificar la terapia de la DM, en el informe" },
  { codigo: "D7910", descripcion: "sutura de heridas peque\u00f1as recientes de hasta 5 cm" },
  { codigo: "D7911", descripcion: "sutura complicado - hasta 5 cm" },
  { codigo: "D7912", descripcion: "sutura complicado - superior a 5 cm" },
  { codigo: "D7920", descripcion: "injertos de piel (identificar defecto cubierto, la ubicaci\u00f3n y el tipo de injerto)" },
  { codigo: "D7940", descripcion: "osteoplastia - de las deformidades ortogn\u00e1tica" },
  { codigo: "D7941", descripcion: "osteotom\u00eda - ramas de la mand\u00edbula" },
  { codigo: "D7943", descripcion: "osteotom\u00eda - ramas de la mand\u00edbula con injerto \u00f3seo" },
  { codigo: "D7944", descripcion: "osteotom\u00eda - segmentado o subapical" },
  { codigo: "D7945", descripcion: "osteotomia-cuerpo de la mand\u00edbula" },
  { codigo: "D7946", descripcion: "LeFort I (maxilar - total)" },
  { codigo: "D7947", descripcion: "LeFort I (maxilar - segmentada)" },
  { codigo: "D7948", descripcion: "de LeFort II o III de LeFort (osteoplastia de los huesos faciales de la hipoplasia del tercio medio facial o retrusi\u00f3n) - sin injerto \u00f3seo" },
  { codigo: "D7949", descripcion: "LeFort II o III de LeFort - con injerto \u00f3seo" },
  { codigo: "D7950", descripcion: "injerto osteoperiosteal, \u00f3seo o de cart\u00edlago de la mand\u00edbula o el maxilar - aut\u00f3geno o no aut\u00f3geno." },
  { codigo: "D7951", descripcion: "elevaciones de seno con hueso o suced\u00e1neos" },
  { codigo: "D7953", descripcion: "injerto \u00f3seo de reemplazo para la preservaci\u00f3n de cresta - por sitio" },
  { codigo: "D7955", descripcion: "reparaci\u00f3n de suave maxilofacial y / o defecto de los tejidos duros" },
  { codigo: "D7960", descripcion: "frenectom\u00eda (o frenotom\u00eda) - procedimiento separado" },
  { codigo: "D7963", descripcion: "frenectoplast\u00eda" },
  { codigo: "D7970", descripcion: "extirpaci\u00f3n de tejido hiperpl\u00e1sico - por arco" },
  { codigo: "D7971", descripcion: "excisi\u00f3n de la enc\u00eda pericoronarios" },
  { codigo: "D7972", descripcion: "reducci\u00f3n quir\u00fargica de la tuberosidad fibrosa" },
  { codigo: "D7980", descripcion: "sialolithotomy" },
  { codigo: "D7981", descripcion: "excisi\u00f3n de las gl\u00e1ndulas salivales" },
  { codigo: "D7982", descripcion: "sialodochoplasty" },
  { codigo: "D7983", descripcion: "cierre de f\u00edstula salival" },
  { codigo: "D7990", descripcion: "traqueotom\u00eda de emergencia" },
  { codigo: "D7991", descripcion: "coronoidectom\u00eda" },
  { codigo: "D7995", descripcion: "injerto sint\u00e9tico - huesos de la mand\u00edbula o la cara" },
  { codigo: "D7996", descripcion: "-implante mandibular con fines de aumento (con exclusi\u00f3n de reborde alveolar)" },
  { codigo: "D7997", descripcion: "retirar el aparato (no por el dentista que coloc\u00f3 aparato), incluye la eliminaci\u00f3n de archbar" },
  { codigo: "D7998", descripcion: "colocaci\u00f3n intraoral de un dispositivo de fijaci\u00f3n no en relaci\u00f3n con una fractura" },
  { codigo: "D7999", descripcion: "sin especificar procedimiento de cirug\u00eda oral, en el informe" },
  { codigo: "D8010", descripcion: "limitado tratamiento ortod\u00f3ncico de la dentici\u00f3n primaria" },
  { codigo: "D8020", descripcion: "limitado tratamiento ortod\u00f3ncico de la dentici\u00f3n de transici\u00f3n" },
  { codigo: "D8030", descripcion: "limitado tratamiento ortod\u00f3ncico de la dentici\u00f3n adolescente" },
  { codigo: "D8040", descripcion: "limitado tratamiento ortod\u00f3ncico de la dentici\u00f3n adulta" },
  { codigo: "D8050", descripcion: "tratamiento interceptivo ortod\u00f3ncico de la dentici\u00f3n primaria" },
  { codigo: "D8060", descripcion: "tratamiento interceptiv ortod\u00f3ncico de la dentici\u00f3n de transici\u00f3n" },
  { codigo: "D8070", descripcion: "tratamiento completo ortod\u00f3ncico de la dentici\u00f3n de transici\u00f3n" },
  { codigo: "D8080", descripcion: "tratamiento completo ortod\u00f3ncico de la dentici\u00f3n adolescente" },
  { codigo: "D8090", descripcion: "tratamiento completo ortod\u00f3ncico de la dentici\u00f3n adulta" },
  { codigo: "D8210", descripcion: "terapia aparato removible" },
  { codigo: "D8220", descripcion: "tratamiento con aparatos fijos" },
  { codigo: "D8660", descripcion: "tratamiento previo a la visita de ortodoncia" },
  { codigo: "D8670", descripcion: "visita peri\u00f3dica del tratamiento de ortodoncia (como parte del contrato)" },
  { codigo: "D8680", descripcion: "ortodoncia de retenci\u00f3n (eliminaci\u00f3n de los aparatos, la construcci\u00f3n y colocaci\u00f3n de retenci\u00f3n (s))" },
  { codigo: "D8690", descripcion: "tratamiento de ortodoncia (facturaci\u00f3n alternativa a una tarifa de contrato)" },
  { codigo: "D8691", descripcion: "reparaci\u00f3n del aparato de ortodoncia" },
  { codigo: "D8692", descripcion: "reemplazo de bracket roto o perdido" },
  { codigo: "D8693", descripcion: "recidimentaci\u00f3n o recementaci\u00f3n, y / o reparaci\u00f3n, seg\u00fan sea necesario, de los retenedores fijos" },
  { codigo: "D8999", descripcion: "sin especificar el procedimiento de ortodoncia" },
  { codigo: "D9110", descripcion: "paliativo (de emergencia) el tratamiento del dolor dental - procedimiento de menores" },
  { codigo: "D9120", descripcion: "pr\u00f3tesis parcial fija de seccionamiento" },
  { codigo: "D9210", descripcion: "anestesia local, no en relaci\u00f3n con procedimientos quir\u00fargicos o quir\u00fargicos" },
  { codigo: "D9211", descripcion: "anestesia regional" },
  { codigo: "D9212", descripcion: "divisi\u00f3n del trig\u00e9mino bloqueo anest\u00e9sico" },
  { codigo: "D9215", descripcion: "anestesia local" },
  { codigo: "D9220", descripcion: "sedaci\u00f3n profunda / anestesia general - primeros 30 minutos" },
  { codigo: "D9221", descripcion: "sedaci\u00f3n profunda / anestesia general - cada 15 minutos adicionales" },
  { codigo: "D9230", descripcion: "analgesia, ansiolisis, la inhalaci\u00f3n de \u00f3xido nitroso" },
  { codigo: "D9241", descripcion: "sedaci\u00f3n intravenosa consciente / analgesia - primeros 30 minutos" },
  { codigo: "D9242", descripcion: "sedaci\u00f3n consciente intravenosa / analgesia - cada 15 minutos adicionales" },
  { codigo: "D9248", descripcion: "sedaci\u00f3n consciente intravenosa no" },
  { codigo: "D9310", descripcion: "consulta de servicio de diagn\u00f3stico proporcionado por el dentista u otro m\u00e9dico que solicita dentista o m\u00e9dico" },
  { codigo: "D9410", descripcion: "casa / llamada ampliado centro de atenci\u00f3n" },
  { codigo: "D9420", descripcion: "llamada del hospital" },
  { codigo: "D9430", descripcion: "visita al consultorio para observaci\u00f3n (durante el horario regular) - no hay otros servicios regulares" },
  { codigo: "D9440", descripcion: "visita al consultorio - despu\u00e9s de las horas regulares" },
  { codigo: "D9450", descripcion: "presentaci\u00f3n del caso, la planificaci\u00f3n del tratamiento detallado y extenso" },
  { codigo: "D9610", descripcion: "terap\u00e9utica drogas por v\u00eda parenteral, administraci\u00f3n \u00fanica" },
  { codigo: "D9612", descripcion: "drogas terap\u00e9uticas parenteral, administraci\u00f3n de dos o m\u00e1s medicamentos diferentes" },
  { codigo: "D9630", descripcion: "otras drogas y / o medicamentos" },
  { codigo: "D9910", descripcion: "aplicaci\u00f3n del medicamento de sensibilizaci\u00f3n" },
  { codigo: "D9911", descripcion: "aplicaci\u00f3n de resina de de sensibilizaci\u00f3n de la superficie del cuello / o de la ra\u00edz, por diente" },
  { codigo: "D9920", descripcion: "manejo de la conducta" },
  { codigo: "D9930", descripcion: "tratamiento de las complicaciones (post-quir\u00fargico) - circunstancias excepcionales" },
  { codigo: "D9940", descripcion: "ajuste oclusal" },
  { codigo: "D9941", descripcion: "fabricaci\u00f3n de protectores bucales deportivos" },
  { codigo: "D9942", descripcion: "reparaci\u00f3n y / o rectificaci\u00f3n de ajuste oclusal" },
  { codigo: "D9950", descripcion: "an\u00e1lisis de la oclusi\u00f3n \u2013 mordida profunda" },
  { codigo: "D9951", descripcion: "ajuste oclusal - limitada" },
  { codigo: "D9952", descripcion: "ajuste oclusal- completa" },
  { codigo: "D9970", descripcion: "microabrasi\u00f3n del esmalte" },
  { codigo: "D9971", descripcion: "odontoplast\u00eda 1-2 dientes; incluye la eliminaci\u00f3n de las proyecciones del esmalte" },
  { codigo: "D9972", descripcion: "blanqueamiento externos - por arco" },
  { codigo: "D9973", descripcion: "blanqueamientos externos - por diente" },
  { codigo: "D9974", descripcion: "blanqueamiento interno - por diente" },
  { codigo: "D9999", descripcion: "sin especificar procedimiento complementario" },
];
